angular.module('ancientOrthodoxWebCalendar.utils', [
  'calendarSystemService',
  'dateValidatorService',
  'dataService',
  'linkToAnchorService',
  'notifyingService',
  'todayService',
  'pageTitleService',
  'pathService',
  'httpInterceptor',
  'russianPluralizeFilter',
  'stateHandlerService',
  'toTrustedFilter',
  'todayService',
  'yearArrayService',
]);
