angular.module('ancientWebCalendar.utils', [
  'calendarSystemService',
  'dateValidatorService',
  'dataService',
  'linkToAnchorService',
  'notifyingService',
  'todayService',
  'pageTitleService',
  'pathService',
  'russianPluralizeFilter',
  'stateHandlerService',
  'toTrustedFilter',
  'todayService',
  'yearArrayService',
]);
